import { useState, useMemo, useEffect } from 'react';
import Modal from '../shared/Modal';
import { db, type Person } from '../../db/database';
import { bulkAddPeople } from '../../db/hooks';
import { CheckCircle2, AlertTriangle, AlertCircle, Eye, Sliders, Table, Sparkles, RefreshCw } from 'lucide-react';

interface ColumnMappingModalProps {
  isOpen: boolean;
  onClose: () => void;
  headers: string[];
  rawRows: Record<string, any>[];
  fileName: string;
  activeFolderId?: number;
  activeFolderName?: string;
  onImportComplete: (count: number) => void;
}

const SYSTEM_FIELDS: { key: keyof Omit<Person, 'id' | 'createdAt'>; label: string; required?: boolean }[] = [
  { key: 'fullName', label: 'Full Name', required: true },
  { key: 'idNumber', label: 'ID Number', required: true },
  { key: 'gender', label: 'Gender / Sex' },
  { key: 'schoolName', label: 'School / Institution' },
  { key: 'grade', label: 'Grade / Class' },
  { key: 'section', label: 'Section' },
  { key: 'rollNumber', label: 'Roll Number' },
  { key: 'department', label: 'Department' },
  { key: 'role', label: 'Role / Designation' },
  { key: 'category', label: 'Category / Group' },
  { key: 'phone', label: 'Phone Number' },
  { key: 'email', label: 'Email Address' },
  { key: 'bloodGroup', label: 'Blood Group' },
  { key: 'joinedDate', label: 'Date Joined / Enrollment' },
  { key: 'guardianName', label: 'Guardian / Parent Name' },
  { key: 'emergencyPhone', label: 'Emergency Contact' },
];

export default function ColumnMappingModal({
  isOpen,
  onClose,
  headers,
  rawRows,
  fileName,
  activeFolderId,
  activeFolderName,
  onImportComplete,
}: ColumnMappingModalProps) {
  // Auto-match initial mapping based on fuzzy header names
  const initialMapping = useMemo(() => {
    const map: Record<string, string> = {};

    headers.forEach(header => {
      const h = header.toLowerCase().replace(/[^a-z0-9]/g, '');

      if (h.includes('studentname') || h.includes('fullname') || h.includes('name')) {
        if (!map['fullName']) map['fullName'] = header;
      } else if (h.includes('idnumber') || h.includes('id') || h.includes('reg') || h.includes('serial') || h.includes('code')) {
        if (!map['idNumber']) map['idNumber'] = header;
      } else if (h.includes('gender') || h.includes('sex')) {
        if (!map['gender']) map['gender'] = header;
      } else if (h.includes('school') || h.includes('institution') || h.includes('campus')) {
        if (!map['schoolName']) map['schoolName'] = header;
      } else if (h.includes('grade') || h.includes('class') || h.includes('standard')) {
        if (!map['grade']) map['grade'] = header;
      } else if (h.includes('section') || h.includes('sec')) {
        if (!map['section']) map['section'] = header;
      } else if (h.includes('roll') || h.includes('rollno') || h.includes('rollnumber')) {
        if (!map['rollNumber']) map['rollNumber'] = header;
      } else if (h.includes('dept') || h.includes('department')) {
        if (!map['department']) map['department'] = header;
      } else if (h.includes('role') || h.includes('title') || h.includes('position')) {
        if (!map['role']) map['role'] = header;
      } else if (h.includes('phone') || h.includes('contact') || h.includes('mobile') || h.includes('tel')) {
        if (!map['phone']) map['phone'] = header;
      } else if (h.includes('email') || h.includes('mail')) {
        if (!map['email']) map['email'] = header;
      } else if (h.includes('blood') || h.includes('bg')) {
        if (!map['bloodGroup']) map['bloodGroup'] = header;
      } else if (h.includes('guardian') || h.includes('parent') || h.includes('father') || h.includes('mother')) {
        if (!map['guardianName']) map['guardianName'] = header;
      } else if (h.includes('emergency')) {
        if (!map['emergencyPhone']) map['emergencyPhone'] = header;
      } else if (h.includes('joined') || h.includes('date') || h.includes('dob')) {
        if (!map['joinedDate']) map['joinedDate'] = header;
      }
    });

    return map;
  }, [headers]);

  const [mapping, setMapping] = useState<Record<string, string>>(initialMapping);
  const [activeTab, setActiveTab] = useState<'mapping' | 'preview'>('mapping');
  const [importing, setImporting] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [existingDbIds, setExistingDbIds] = useState<Set<string>>(new Set());
  const [skipDuplicates, setSkipDuplicates] = useState(true);
  const [autoGenerateDuplicateIds, setAutoGenerateDuplicateIds] = useState(false);

  // Fetch existing ID numbers from IndexedDB for duplicate checks
  useEffect(() => {
    if (!isOpen) return;
    db.people.toArray().then(people => {
      const ids = new Set(people.map(p => p.idNumber?.trim().toLowerCase()).filter(Boolean));
      setExistingDbIds(ids);
    }).catch(console.error);
  }, [isOpen]);

  const handleFieldChange = (systemKey: string, excelHeader: string) => {
    setMapping(prev => ({
      ...prev,
      [systemKey]: excelHeader,
    }));
  };

  // Pre-process and validate mapped rows
  const validationResults = useMemo(() => {
    let validCount = 0;
    let missingNameCount = 0;
    let internalDupCount = 0;
    let dbDupCount = 0;

    const seenInImport = new Set<string>();

    const mappedRows = rawRows.map((row, idx) => {
      const nameVal = mapping['fullName'] ? String(row[mapping['fullName']] || '').trim() : '';
      let idVal = mapping['idNumber'] ? String(row[mapping['idNumber']] || '').trim() : '';
      if (!idVal) {
        idVal = `SL-${new Date().getFullYear()}-${1000 + idx}`;
      }

      const isMissingName = !nameVal;
      const lowerId = idVal.toLowerCase();
      const isInternalDup = seenInImport.has(lowerId);
      const isDbDup = existingDbIds.has(lowerId);

      if (isMissingName) missingNameCount++;
      if (isInternalDup) internalDupCount++;
      if (isDbDup && !isInternalDup) dbDupCount++;

      seenInImport.add(lowerId);

      const isValid = !isMissingName && (!isInternalDup || autoGenerateDuplicateIds) && (!isDbDup || autoGenerateDuplicateIds || !skipDuplicates);
      if (isValid) validCount++;

      return {
        originalRow: row,
        name: nameVal || `(Missing Name - Row ${idx + 1})`,
        idNumber: idVal,
        gender: mapping['gender'] ? String(row[mapping['gender']] || '') : '',
        schoolName: mapping['schoolName'] ? String(row[mapping['schoolName']] || '') : '',
        grade: mapping['grade'] ? String(row[mapping['grade']] || '') : '',
        section: mapping['section'] ? String(row[mapping['section']] || '') : '',
        rollNumber: mapping['rollNumber'] ? String(row[mapping['rollNumber']] || '') : '',
        department: mapping['department'] ? String(row[mapping['department']] || '') : '',
        role: mapping['role'] ? String(row[mapping['role']] || '') : '',
        phone: mapping['phone'] ? String(row[mapping['phone']] || '') : '',
        email: mapping['email'] ? String(row[mapping['email']] || '') : '',
        bloodGroup: mapping['bloodGroup'] ? String(row[mapping['bloodGroup']] || '') : '',
        joinedDate: mapping['joinedDate'] ? String(row[mapping['joinedDate']] || '') : '',
        guardianName: mapping['guardianName'] ? String(row[mapping['guardianName']] || '') : '',
        emergencyPhone: mapping['emergencyPhone'] ? String(row[mapping['emergencyPhone']] || '') : '',
        isMissingName,
        isInternalDup,
        isDbDup,
      };
    });

    return {
      mappedRows,
      validCount,
      missingNameCount,
      internalDupCount,
      dbDupCount,
      totalDuplicates: internalDupCount + dbDupCount,
    };
  }, [rawRows, mapping, existingDbIds, skipDuplicates, autoGenerateDuplicateIds]);

  const handleImport = async () => {
    setErrorMsg(null);
    if (!mapping['fullName']) {
      setErrorMsg('WHAT: Full Name is not mapped.\nWHY: Every card record requires an identifiable personnel name.\nNEXT: Select a spreadsheet column for "Full Name" above.');
      return;
    }

    setImporting(true);
    try {
      const recordsToInsert: Omit<Person, 'id'>[] = [];
      const seenIds = new Set<string>();

      validationResults.mappedRows.forEach((r, i) => {
        // Skip invalid rows if missing name
        if (r.isMissingName) return;

        let finalId = r.idNumber;
        const lowerId = finalId.toLowerCase();

        // Handle duplicates
        if (seenIds.has(lowerId) || existingDbIds.has(lowerId)) {
          if (autoGenerateDuplicateIds) {
            finalId = `SL-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}${i}`;
          } else if (skipDuplicates) {
            return; // Skip duplicate
          }
        }

        seenIds.add(finalId.toLowerCase());

        recordsToInsert.push({
          fullName: r.name,
          idNumber: finalId,
          gender: (r.gender as any) || 'Male',
          schoolName: r.schoolName || 'SiliconLabs Academy',
          grade: r.grade || r.department || 'Grade 10',
          section: r.section || 'A',
          rollNumber: r.rollNumber || `${i + 1}`,
          category: (mapping['category'] ? String(r.originalRow[mapping['category']] || '') : '') || 'Students',
          department: r.department || r.grade || 'General',
          role: r.role || 'Student',
          phone: r.phone || '',
          email: r.email || `${r.name.toLowerCase().replace(/\s+/g, '.')}@siliconlabs.internal`,
          bloodGroup: r.bloodGroup || 'O+',
          joinedDate: r.joinedDate || new Date().toISOString().split('T')[0],
          guardianName: r.guardianName || '',
          emergencyPhone: r.emergencyPhone || '',
          photoDataUrl: '',
          batchFolderId: activeFolderId,
          folderName: activeFolderName || 'Student Intake',
          sourceFileName: fileName,
          status: 'Active',
          fulfillmentStatus: 'Unfulfilled',
          paymentStatus: 'Paid',
          channel: 'Spreadsheet Import',
          totalAmount: 'Free',
          workerId: 1,
          collectedBy: 'Data Import Station',
          location: r.schoolName || 'Onboarding Queue',
          createdAt: new Date(),
        });
      });

      if (recordsToInsert.length === 0) {
        setErrorMsg('WHAT: No valid records found to import.\nWHY: All rows were either missing required names or flagged as duplicate IDs.\nNEXT: Adjust duplicate resolution options below or correct your spreadsheet.');
        setImporting(false);
        return;
      }

      await bulkAddPeople(recordsToInsert);
      onImportComplete(recordsToInsert.length);
      onClose();
    } catch (err) {
      console.error('Import failed:', err);
      setErrorMsg(`WHAT: Failed to insert records into database.\nWHY: ${err instanceof Error ? err.message : 'Database error'}\nNEXT: Check your browser storage quota and try again.`);
    } finally {
      setImporting(false);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Spreadsheet Importer & Field Validator"
      size="lg"
    >
      <div className="space-y-4 font-sans text-xs" style={{ color: 'var(--text-primary)' }}>
        
        {errorMsg && (
          <div className="p-3.5 rounded-xl border border-red-500/40 bg-red-500/10 text-red-400 whitespace-pre-line font-medium text-[11px] leading-relaxed">
            {errorMsg}
          </div>
        )}

        {/* File Info & Navigation Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between p-3 rounded-xl border gap-2 text-xs" style={{ backgroundColor: 'var(--bg-elevated)', borderColor: 'var(--border-primary)' }}>
          <div className="flex items-center gap-2">
            <span className="font-mono text-[#9fe870] font-bold">SOURCE:</span>
            <span className="font-semibold">{fileName}</span>
            {activeFolderName && <span className="font-mono text-[#10b981] ml-1.5 font-medium">({activeFolderName})</span>}
          </div>
          <div className="flex items-center gap-2">
            <div className="flex rounded-lg p-0.5 border" style={{ backgroundColor: 'var(--bg-surface)', borderColor: 'var(--border-primary)' }}>
              <button
                type="button"
                onClick={() => setActiveTab('mapping')}
                className={`px-3 py-1 rounded-md text-xs font-semibold flex items-center gap-1.5 transition-all ${
                  activeTab === 'mapping' ? 'bg-[#9fe870] text-[#080c10] shadow-xs' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Sliders className="w-3 h-3" />
                Mapping ({Object.keys(mapping).filter(k => mapping[k]).length}/{SYSTEM_FIELDS.length})
              </button>
              <button
                type="button"
                onClick={() => setActiveTab('preview')}
                className={`px-3 py-1 rounded-md text-xs font-semibold flex items-center gap-1.5 transition-all ${
                  activeTab === 'preview' ? 'bg-[#9fe870] text-[#080c10] shadow-xs' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Eye className="w-3 h-3" />
                Preview & Validate ({rawRows.length})
              </button>
            </div>
          </div>
        </div>

        {/* Validation Summary Badges */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px]">
          <div className="p-2.5 rounded-xl border flex items-center justify-between" style={{ backgroundColor: 'var(--bg-surface)', borderColor: 'var(--border-primary)' }}>
            <span style={{ color: 'var(--text-muted)' }}>Total In File:</span>
            <span className="font-bold font-mono text-slate-200">{rawRows.length}</span>
          </div>
          <div className="p-2.5 rounded-xl border border-emerald-500/20 bg-emerald-500/5 flex items-center justify-between">
            <span className="text-emerald-400 font-medium">Ready:</span>
            <span className="font-bold font-mono text-emerald-300">{validationResults.validCount}</span>
          </div>
          <div className={`p-2.5 rounded-xl border flex items-center justify-between ${validationResults.totalDuplicates > 0 ? 'border-amber-500/30 bg-amber-500/10 text-amber-400' : 'border-slate-800 bg-slate-900/40 text-slate-400'}`}>
            <span>Duplicate IDs:</span>
            <span className="font-bold font-mono">{validationResults.totalDuplicates}</span>
          </div>
          <div className={`p-2.5 rounded-xl border flex items-center justify-between ${validationResults.missingNameCount > 0 ? 'border-rose-500/30 bg-rose-500/10 text-rose-400' : 'border-slate-800 bg-slate-900/40 text-slate-400'}`}>
            <span>Missing Name:</span>
            <span className="font-bold font-mono">{validationResults.missingNameCount}</span>
          </div>
        </div>

        {activeTab === 'mapping' ? (
          /* Mapping Configuration Tab */
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-xs font-bold uppercase tracking-wider font-mono text-slate-400">
                System Field Mapping
              </h4>
              <span className="text-[10px] text-slate-400">
                Auto-matched with high confidence
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 max-h-72 overflow-y-auto pr-1">
              {SYSTEM_FIELDS.map(field => {
                const currentVal = mapping[field.key] || '';
                return (
                  <div
                    key={field.key}
                    className="p-2.5 rounded-xl border flex flex-col justify-between transition-all"
                    style={{ backgroundColor: 'var(--bg-elevated)', borderColor: currentVal ? 'rgba(159, 232, 112, 0.25)' : 'var(--border-primary)' }}
                  >
                    <div className="flex items-center justify-between mb-1.5">
                      <label className="text-xs font-semibold mb-0 flex items-center gap-1">
                        {field.label} {field.required && <span className="text-red-400">*</span>}
                        {currentVal && <CheckCircle2 className="w-3 h-3 text-[#9fe870]" />}
                      </label>
                      <span className="text-[10px] font-mono text-slate-400">{field.key}</span>
                    </div>

                    <select
                      value={currentVal}
                      onChange={e => handleFieldChange(field.key, e.target.value)}
                      className="w-full text-xs py-1.5 px-2 rounded-lg border font-medium focus:outline-none focus:border-[#9fe870] cursor-pointer"
                      style={{ backgroundColor: 'var(--bg-surface)', borderColor: 'var(--border-primary)', color: 'var(--text-primary)' }}
                    >
                      <option value="">-- Do not map --</option>
                      {headers.map(h => (
                        <option key={h} value={h}>
                          Column: {h}
                        </option>
                      ))}
                    </select>
                  </div>
                );
              })}
            </div>
          </div>
        ) : (
          /* Preview & Validation Tab */
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-xs font-bold uppercase tracking-wider font-mono text-slate-400">
                Mapped Sample Preview (First 5 Rows)
              </h4>
              <span className="text-[10px] text-slate-400">
                Showing hydration validation
              </span>
            </div>

            <div className="border rounded-xl overflow-x-auto max-h-60" style={{ borderColor: 'var(--border-primary)', backgroundColor: 'var(--bg-surface)' }}>
              <table className="w-full text-[11px] text-left">
                <thead>
                  <tr className="border-b text-slate-400 font-mono" style={{ borderColor: 'var(--border-primary)', backgroundColor: 'var(--bg-elevated)' }}>
                    <th className="p-2">Status</th>
                    <th className="p-2">Full Name</th>
                    <th className="p-2">ID Number</th>
                    <th className="p-2">Grade/Dept</th>
                    <th className="p-2">Role</th>
                    <th className="p-2">Phone</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/40">
                  {validationResults.mappedRows.slice(0, 5).map((r, i) => (
                    <tr key={i} className="hover:bg-slate-800/20">
                      <td className="p-2">
                        {r.isMissingName ? (
                          <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-rose-500/20 text-rose-300">No Name</span>
                        ) : r.isDbDup ? (
                          <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-amber-500/20 text-amber-300">DB Duplicate</span>
                        ) : r.isInternalDup ? (
                          <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-amber-500/20 text-amber-300">File Duplicate</span>
                        ) : (
                          <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-emerald-500/20 text-emerald-300">Valid</span>
                        )}
                      </td>
                      <td className="p-2 font-semibold text-slate-200">{r.name}</td>
                      <td className="p-2 font-mono text-slate-300">{r.idNumber}</td>
                      <td className="p-2 text-slate-400">{r.grade || r.department || '—'}</td>
                      <td className="p-2 text-slate-400">{r.role || 'Student'}</td>
                      <td className="p-2 font-mono text-slate-400">{r.phone || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Duplicate Handling Options */}
            <div className="p-3 rounded-xl border text-[11px] space-y-2" style={{ backgroundColor: 'var(--bg-elevated)', borderColor: 'var(--border-primary)' }}>
              <span className="font-bold text-slate-200">Duplicate Resolution Strategy:</span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <label className="flex items-center gap-2 cursor-pointer text-slate-300">
                  <input
                    type="radio"
                    name="dupStrategy"
                    checked={skipDuplicates && !autoGenerateDuplicateIds}
                    onChange={() => { setSkipDuplicates(true); setAutoGenerateDuplicateIds(false); }}
                    className="accent-[#9fe870]"
                  />
                  <span>Skip duplicate ID records safely</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer text-slate-300">
                  <input
                    type="radio"
                    name="dupStrategy"
                    checked={autoGenerateDuplicateIds}
                    onChange={() => { setAutoGenerateDuplicateIds(true); setSkipDuplicates(false); }}
                    className="accent-[#9fe870]"
                  />
                  <span>Auto-assign new unique ID on duplicate</span>
                </label>
              </div>
            </div>
          </div>
        )}

        {/* Actions */}
        <div className="flex items-center justify-between pt-3 border-t" style={{ borderColor: 'var(--border-primary)' }}>
          <div className="text-[11px] text-slate-400 font-mono">
            {validationResults.validCount} valid records selected
          </div>

          <div className="flex items-center gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-xs font-semibold rounded-xl border hover:opacity-80 cursor-pointer"
              style={{ backgroundColor: 'var(--bg-elevated)', borderColor: 'var(--border-primary)', color: 'var(--text-secondary)' }}
            >
              Cancel
            </button>

            <button
              type="button"
              onClick={handleImport}
              disabled={importing || !mapping['fullName'] || validationResults.validCount === 0}
              className="btn-primary py-2 px-6 text-xs font-bold flex items-center gap-1.5 shadow-xs cursor-pointer disabled:opacity-50"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>{importing ? 'Importing records…' : `Import ${validationResults.validCount} Verified Records`}</span>
            </button>
          </div>
        </div>
      </div>
    </Modal>
  );
}
